### ISSUE TITLE
Error Code: ImageNotFound

### ISSUE THREAD

**Issue by AaronZhangL** [Azure/AzureStack-QuickStart-Templates#190]
Thanks for your work.
I got the below error when I try to deploy template [101-simple-linux-vm] via azure stack portal [Microsoft.Template->Error details]

--error detail--
> At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/arm-debug for usage details. (Code: DeploymentFailed)
> The platform image 'Canonical:UbuntuServer:14.04.3-LTS:latest' is not available. Verify that all fields in the storage profile are correct. (Code: ImageNotFound)

How to fix it?
thanks
-Aaron

**Comment by radhikagupta5** [comment]
You need to download the required VHD from market place:
https://docs.microsoft.com/en-us/azure/azure-stack/azure-stack-download-azure-marketplace-item

Once the VHD is available in your platform image repository, this should just work.

**Comment by knithinc** [comment]
Closing the issue due to inactivity. Please re-open if this still exists.
