### ISSUE TITLE
mysql-standalone-server-windows - update to current images

### ISSUE THREAD

**Issue by JeffGoldner** [Azure/AzureStack-QuickStart-Templates#241]
"5.7": "https://dev.mysql.com/get/Downloads/MySQL-5.7/mysql-5.7.18-winx64.zip",
		"5.6": "https://dev.mysql.com/get/Downloads/MySQL-5.6/mysql-5.6.36-winx64.zip",
		"5.5": "https://dev.mysql.com/get/Downloads/MySQL-5.5/mysql-5.5.56-winx64.zip"

**Comment by knithinc** [comment]
Fixed.
