### ISSUE TITLE
101-acsengine-docker-swarmmode deployment successfull but swarm not deployed

### ISSUE THREAD

**Issue by bottkars** [Azure/AzureStack-QuickStart-Templates#289]
AzureStack-QuickStart-Templates/101-acsengine-docker-swarmmode/ ran successfull, however, docker swarmmode is not configured. there ius also no output log from configure-swarmmode-cluster.sh
.

Docker has been isnatllerd however with 17.06 but unable to start

**Comment by radhikagupta5** [comment]
This is fixed now.

**Comment by knithinc** [comment]
Looks like the issue is fixed, and also since the bug has been inactive this long, closing it. Please file a new issue if you are still running into the same.
