### ISSUE TITLE
Failing SharePoint DSC Configuration

### ISSUE THREAD

**Issue by joseq-terawe** [Azure/AzureStack-QuickStart-Templates#297]
I am getting an error when trying to provision the SharePoint 2013 non-Ha template in Azure Stack. Most of the template deploys correctly, but when trying to configure the SharePoint server I am constantly getting this error. Has anyone encountered this error if so how was this error fixed? thanks

Here is the error that Azure Stack is throwing:

{"code":"DeploymentFailed","message":"At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/arm-debug for usage details.","details":[{"code":"Conflict","message":"{\r\n \"status\": \"Failed\",\r\n \"error\": {\r\n \"code\": \"ResourceDeploymentFailure\",\r\n \"message\": \"The resource operation completed with terminal provisioning state 'Failed'.\",\r\n \"details\": [\r\n {\r\n \"code\": \"VMExtensionProvisioningError\",\r\n \"message\": \"VM has reported a failure when processing extension 'ConfigureSPServer'. Error message: DSC Configuration 'InstallAndConfigureSharePointServer' completed with error(s). Following are the first few: PowerShell DSC resource MSFT_xSPInstall failed to execute Set-TargetResource functionality with error message: SharePoint install failed, exit code was 30066 The SendConfigurationApply function did not succeed.\"\r\n }\r\n ]\r\n }\r\n}"}]}

**Comment by Jquintero190** [comment]
here is the whole error message when checking through vmextention blade of the SharePoint VM:

[
    {
        "code": "ComponentStatus/DscConfigurationLog/failed/8",
        "level": "Error",
        "displayStatus": "Provisioning failed",
        "message": "[2017-09-26 18:36:22Z] [VERBOSE] [SPSPTEST3]:                            [[xADUser]CreateFarmAccount] The password for user 'sa' is valid.\r\n[2017-09-26 18:36:22Z] [VERBOSE] [SPSPTEST3]: LCM:  [ End    Test     ]  [[xADUser]CreateFarmAccount]  in 0.2810 seconds.\r\n[2017-09-26 18:36:22Z] [VERBOSE] [SPSPTEST3]: LCM:  [ Skip   Set      ]  [[xADUser]CreateFarmAccount]\r\n[2017-09-26 18:36:22Z] [VERBOSE] [SPSPTEST3]: LCM:  [ End    Resource ]  [[xADUser]CreateFarmAccount]\r\n[2017-09-26 18:36:22Z] [VERBOSE] [SPSPTEST3]: LCM:  [ End    Set      ]\r\n[2017-09-26 18:36:22Z] [ERROR] The SendConfigurationApply function did not succeed.\r\n[2017-09-26 18:36:22Z] [VERBOSE] Operation 'Invoke CimMethod' complete.\r\n[2017-09-26 18:36:22Z] [VERBOSE] Time taken for configuration job to complete is 41.313 seconds\r\n[2017-09-26 18:36:27Z] [VERBOSE] Performing the operation \"Start-DscConfiguration: SendMetaConfigurationApply\" on target \"MSFT_DSCLocalConfigurationManager\".\r\n[2017-09-26 18:36:27Z] [VERBOSE] Perform operation 'Invoke CimMethod' with following parameters, ''methodName' = SendMetaConfigurationApply,'className' = MSFT_DSCLocalConfigurationManager,'namespaceName' = root/Microsoft/Windows/DesiredStateConfiguration'.\r\n[2017-09-26 18:36:27Z] [VERBOSE] An LCM method call arrived from computer SPSPTEST3 with user sid S-1-5-18.\r\n[2017-09-26 18:36:27Z] [VERBOSE] [SPSPTEST3]: LCM:  [ Start  Set      ]\r\n[2017-09-26 18:36:27Z] [VERBOSE] [SPSPTEST3]: LCM:  [ Start  Resource ]  [MSFT_DSCMetaConfiguration]\r\n[2017-09-26 18:36:27Z] [VERBOSE] [SPSPTEST3]: LCM:  [ Start  Set      ]  [MSFT_DSCMetaConfiguration]\r\n[2017-09-26 18:36:27Z] [VERBOSE] [SPSPTEST3]: LCM:  [ End    Set      ]  [MSFT_DSCMetaConfiguration]  in 0.0160 seconds.\r\n[2017-09-26 18:36:27Z] [VERBOSE] [SPSPTEST3]: LCM:  [ End    Resource ]  [MSFT_DSCMetaConfiguration]\r\n[2017-09-26 18:36:27Z] [VERBOSE] [SPSPTEST3]: LCM:  [ End    Set      ]\r\n[2017-09-26 18:36:27Z] [VERBOSE] [SPSPTEST3]: LCM:  [ End    Set      ]    in  0.0780 seconds.\r\n[2017-09-26 18:36:27Z] [VERBOSE] Operation 'Invoke CimMethod' complete.\r\n[2017-09-26 18:36:27Z] [VERBOSE] Set-DscLocalConfigurationManager finished in 0.215 seconds."
    },
    {
        "code": "ComponentStatus/DscExtensionLog/failed/8",
        "level": "Error",
        "displayStatus": "Provisioning failed",
        "message": "[2017-09-26 18:35:19Z] Extension request for sequence number 0 attempting to acquire lock.0 file\r\n[2017-09-26 18:35:20Z] Extension request for sequence number 0 attempting to acquire lock file\r\n[2017-09-26 18:35:20Z] File lock does not exist: begin processing\r\n[2017-09-26 18:35:20Z] Starting DSC Extension ...\r\n[2017-09-26 18:35:20Z] Getting handler execution status HKLM:\\SOFTWARE\\Microsoft\\Azure\\DSC\\2.26.0.0\\Status ...\r\n[2017-09-26 18:35:20Z] Getting handler execution status HKLM:\\SOFTWARE\\Microsoft\\Azure\\DSC\\2.26.0.0\\Status ...\r\n[2017-09-26 18:35:20Z] Reading handler settings from C:\\Packages\\Plugins\\Microsoft.Powershell.DSC\\2.26.0.0\\RuntimeSettings\\0.settings\r\n[2017-09-26 18:35:20Z] Found protected settings on Azure VM. Decrypting.\r\n[2017-09-26 18:35:34Z] Getting handler execution status HKLM:\\SOFTWARE\\Microsoft\\Azure\\DSC\\2.26.0.0\\Status ...\r\n[2017-09-26 18:35:34Z] Getting handler execution status HKLM:\\SOFTWARE\\Microsoft\\Azure\\DSC\\2.26.0.0\\Status ...\r\n[2017-09-26 18:35:35Z] Updating execution status (HKLM:\\SOFTWARE\\Microsoft\\Azure\\DSC\\2.26.0.0\\Status)\r\n[2017-09-26 18:35:35Z] Settings handler status to 'transitioning' (C:\\Packages\\Plugins\\Microsoft.Powershell.DSC\\2.26.0.0\\Status\\0.status)\r\n[2017-09-26 18:35:35Z] Will continue the existing configuration. Executing Start-DscConfiguration...\r\n[2017-09-26 18:35:39Z] Settings handler status to 'transitioning' (C:\\Packages\\Plugins\\Microsoft.Powershell.DSC\\2.26.0.0\\Status\\0.status)\r\n[2017-09-26 18:36:24Z] Settings handler status to 'transitioning' (C:\\Packages\\Plugins\\Microsoft.Powershell.DSC\\2.26.0.0\\Status\\0.status)\r\n[2017-09-26 18:36:26Z] LCM state is PendingConfiguration\r\n[2017-09-26 18:36:26Z] DSC configuration completed.\r\n[2017-09-26 18:36:26Z] Resetting metaconfiguration...\r\n[2017-09-26 18:36:26Z] Restoring C:\\Packages\\Plugins\\Microsoft.Powershell.DSC\\2.26.0.0\\DSCWork\\InstallAndConfigureSharePointServer.ps1.0\\InstallAndConfigureSharePointServer\\localhost.meta.mof.bk...\r\n[2017-09-26 18:36:26Z] Executing Set-DscLocalConfigurationManager...\r\n[2017-09-26 18:36:26Z] Settings handler status to 'transitioning' (C:\\Packages\\Plugins\\Microsoft.Powershell.DSC\\2.26.0.0\\Status\\0.status)\r\n[2017-09-26 18:36:29Z] Settings handler status to 'transitioning' (C:\\Packages\\Plugins\\Microsoft.Powershell.DSC\\2.26.0.0\\Status\\0.status)\r\n[2017-09-26 18:36:29Z] Get-DscLocalConfigurationManager: \r\n\r\nActionAfterReboot              : ContinueConfiguration\r\nAgentId                        : 73BCA8D8-A2E3-11E7-80C5-001DD8B71C0D\r\nAllowModuleOverWrite           : False\r\nCertificateID                  : B7654E3856AE1D834C0237B053AED903D2EEB418\r\nConfigurationDownloadManagers  : {}\r\nConfigurationID                : \r\nConfigurationMode              : ApplyOnly\r\nConfigurationModeFrequencyMins : 15\r\nCredential                     : \r\nDebugMode                      : {NONE}\r\nDownloadManagerCustomData      : \r\nDownloadManagerName            : \r\nLCMCompatibleVersions          : {1.0, 2.0}\r\nLCMState                       : PendingConfiguration\r\nLCMStateDetail                 : \r\nLCMVersion                     : 2.0\r\nStatusRetentionTimeInDays      : 10\r\nSignatureValidationPolicy      : NONE\r\nSignatureValidations           : {}\r\nMaximumDownloadSizeMB          : 500\r\nPartialConfigurations          : \r\nRebootNodeIfNeeded             : True\r\nRefreshFrequencyMins           : 30\r\nRefreshMode                    : PUSH\r\nReportManagers                 : {}\r\nResourceModuleManagers         : {}\r\nPSComputerName                 : \r\n\r\n\r\n\r\n\r\n[2017-09-26 18:36:29Z] Settings handler status to 'error' (C:\\Packages\\Plugins\\Microsoft.Powershell.DSC\\2.26.0.0\\Status\\0.status)"
    },
    {
        "code": "ComponentStatus/Metadata/Succeeded",
        "level": "Info",
        "displayStatus": "Provisioning Succeeded",
        "message": "AgentID=73BCA8D8-A2E3-11E7-80C5-001DD8B71C0D;VMUUID=FBE08A75-8D69-4303-8E4D-28791EC28738"
    }
]

**Comment by knithinc** [comment]
Closing this issue. Please reactivate if needed.
