### ISSUE TITLE
SQL HA template needs to be updated for SQL 2017

### ISSUE THREAD

**Issue by JeffGoldner** [Azure/AzureStack-QuickStart-Templates#335]
Currently hard-coded for SQL2016SP1

**Comment by JeffGoldner** [comment]
New SQL AlwaysOn template replaces the SQL-2016-HA template. It includes 2016 SP1 & SP2, but 2017 does not deploy reliably so it was omitted. There is an issue in one of the final DSC resources.

**Comment by knithinc** [comment]
This seems to be fixed. Closing issue.
