### ISSUE TITLE
url vmExtensionScriptLocation

### ISSUE THREAD

**Issue by chandrakn** [Azure/AzureStack-QuickStart-Templates#359]
Hi MS Team,
What is this URL "https://raw.githubusercontent.com/Azure/azurestack-quickstart-templates/master/appservice-fileserver-standalone" stand for ?

I found that link in vmExtensionScriptLocation section, but I can't directly access that link from browser. Is that URL reachable or is it broken link?

**Comment by cblackuk** [comment]
@chandrakn 
This is why:
IT is a parameter set here:

"vmExtensionScriptLocation": {
      "type": "string",
"defaultValue": "https://raw.githubusercontent.com/Azure/azurestack-quickstart-templates/master/appservice-fileserver-standalone",

And it is then used here: 

 "[concat(parameters('vmExtensionScriptLocation'), '/scripts/OnStartAzureVirtualMachineFileServer.ps1')]",
"[concat(parameters('vmExtensionScriptLocation'), '/scripts/fileserver.cr.zip')]"

Same principal applies to BaseURLs

**Comment by marcvaneijk** [comment]
Closing issue. @chandrakn please reopen if the question is not fully answered yet.
