### ISSUE TITLE
sql-2016-alwayson - VM extension issues

### ISSUE THREAD

**Issue by DarrylvanderPeijl** [Azure/AzureStack-QuickStart-Templates#371]
Hi @JeffGoldner,

I seem to have issues with the new SQL always on template. Everything goes fine untill the extention, giving these errors:

One or more VM extension handlers failed to resolve for VM 'priDC-zo'. Please check individual extension status for more details.

{"code":"DeploymentFailed","message":"At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/arm-debug for usage details.","details":[{"code":"Conflict","message":"{\r\n \"status\": \"Failed\",\r\n \"error\": {\r\n \"code\": \"ResourceDeploymentFailure\",\r\n \"message\": \"The resource operation completed with terminal provisioning state 'Failed'.\",\r\n \"details\": [\r\n {\r\n \"code\": \"VMExtensionProvisioningError\",\r\n \"message\": \"One or more VM extension handlers failed to resolve for VM 'priDC-zo'. Please check individual extension status for more details.\"\r\n }\r\n ]\r\n }\r\n}"}]}

When I check extension under the VM in the portal I dont get any info:

![image](https://user-images.githubusercontent.com/11892641/45224166-9303e500-b2b9-11e8-91aa-ece97061ca4d.png)

Running multinode on 1807.

**Comment by JeffGoldner** [comment]
Can you confirm that you downloaded the latest DSC and CustomScript extensions from the marketplace?

**Comment by DarrylvanderPeijl** [comment]
Thanks Jeff, looks like the latest DSC extension was the issue.
