### ISSUE TITLE
AzureRM Hybrid Profile discrepancy

### ISSUE THREAD

**Issue by rohernan** [Azure/AzureStack-QuickStart-Templates#434]
Team,

For example the 101-vm-windows-create template located here contains this code:
https://github.com/Azure/AzureStack-QuickStart-Templates/blob/master/101-vm-windows-create/azuredeploy.json

"$schema": "https://schema.management.azure.com/schemas/2015-01-01/deploymentTemplate.json#",
    "contentVersion": "1.0.0.0",
    **"apiProfile": "2018-03-01-hybrid",**
    "parameters": {

As noted the apiProfile is 2018-03-01-hybrid is stated; however, according to this external MS doc: https://docs.microsoft.com/en-us/azure-stack/operator/azure-stack-powershell-install

it states: 
You don't need to install AzureRM.Bootstrapper to install the modules for Azure stack version 1901 or later.
**Don't install the 2018-03-01-hybrid profile in addition to using the above AzureRM modules on Azure Stack version 1901 or later.**

So which is it - install the 2018-03-01-hybrid profile or not.  Because you need this in order to deploy it?

**Comment by knithinc** [comment]
@rohernan , the instructions on that page keep changing per AzS release and also per API Profile release. We are working on keeping all the API Profiles specific information in the docs. 
That being said, to deploy the template you don't necessarily need anything on the client side. As long as the Profile is available in Azure/Azure Stack, you will be able to deploy the template. Let me know if this doesn't make sense.
