### ISSUE TITLE
Storage account mismatch with current online version

### ISSUE THREAD

**Issue by oising** [Azure/AzureStack-QuickStart-Templates#84]
The version of the template in this repository seems to use a standard storage account `standard_LRS` whereas deploying in Azure marketplace provisions a premium one -- This cost me my entire monthly budget in three days. Please correct this, or use 72 point red blinking text on the portal provisioning wizard. You say we're only billed for VMs, but my storage account burned up $100 in a few days? I don't even know how that works from a billing and consumption perspective! You're returning to the opaque Azure of old, not to mention this 1999-era return to arcane configuration syntax. Json is even more brain dead than XML is.

**Comment by oising** [comment]
I'm talking about thte sharepoint non-ha farm template, fyi.

**Comment by JesusAlvarezTorres** [comment]
Hi,
I am very sorry to hear this happened to you. The templates that are published on this repo are meant to be deployed on Azure Stack. For Technical Preview Azure Stack supports only standard_LRS storage accounts, thus the SharePoint template on this repo is using standard_LRS. If you need a SharePoint template for Azure you can check out the ones available at: https://github.com/azure/azure-quickstart-templates. 
Azure SharePoint 3 VM: https://github.com/Azure/azure-quickstart-templates/tree/master/sharepoint-three-vm
Azure SharePoint HA: https://github.com/Azure/azure-quickstart-templates/tree/master/sharepoint-server-farm-ha
