### ISSUE TITLE
SharePoint deployment, where can I get the needed images.

### ISSUE THREAD

**Issue by paule96** [Azure/AzureStack-QuickStart-Templates#88]
Hello,

I have a question to the note on this  [Site](https://github.com/Azure/AzureStack-QuickStart-Templates/tree/master/sharepoint-2013-non-ha).
In the Note section of this site is a descritpion that means, I do Need some images. But where I can get this images? Can I downloaded this from the public Azure and can put in my private Azure Stack?

**Comment by JesusAlvarezTorres** [comment]
Hi,
There is no need for specific images to use the SharePoint template. The template will work with the default image available on Azure Stack. The template will take care of downloading the installer bits for SQL and SharePoint during VM configuration. In fact, one of the parameters for this template is a download location for the SharePoint installer bits. The wording on the readme is confusing, I will update it soon.

**Comment by paule96** [comment]
Ah okay. Can I use the direct link from MSDN for this, or must I maybe use the EvalCenter Version?
Or is it besser to save the Iso to a Azure Blob Storage and share it?

**Comment by paule96** [comment]
Okay, thanks for your support 👍
