### ISSUE TITLE
ad-no-ha variables not correct

### ISSUE THREAD

**Issue by paule96** [Azure/AzureStack-QuickStart-Templates#90]
Hello,

in the template for the ad-no-ha ([Site](https://github.com/Azure/AzureStack-QuickStart-Templates/blob/master/ad-non-ha/azuredeploy.json)) in the azuredeploy.json is a bug on line 53.
The line is:
"dnsPrefix": "[concat('ADDNS',resourceGroup().name)]",
but it must be that:
"dnsPrefix": "[toLower(concat('ADDNS',resourceGroup().name))]",

Good luck to fix it :)

**Comment by marcvaneijk** [comment]
@paule96 Thx for your feedback. Can you please submit a pull request with your proposed code. Thanks!
