### ISSUE TITLE
Please make download links for SQL as Parameter

### ISSUE THREAD

**Issue by paule96** [Azure/AzureStack-QuickStart-Templates#91]
Hi guys,

can we put the link for the download source for [SQL Server 2014](https://github.com/Azure/AzureStack-QuickStart-Templates/tree/master/sql-2014-non-ha) as a Parameter with Default value.
Here in my demolap for Azure Stack I don't have a big Internet Connection and a deployment takes along time, if I must download the files from the Internet. The template for SharePoint have a optional Source Parameter and I can but the source in my local Blob storage.
# UPDATE

Please edit the SharePoint template also, because if I use my custom link on my local blob storage, it want a trusted Connection to the https URL on my blob storage. This means you can't deploy SharePoint if you use your own private blobstorage....
To do this you must for example by the DSC Config for SQL Server 2014 in the file xDownloadISO.psm1 insert a line befor line 50 with this content:
`[System.Net.ServicePointManager]::ServerCertificateValidationCallback = {$true}`
and after line line 51 a line with this content:
`[System.Net.ServicePointManager]::ServerCertificateValidationCallback = null`
[more Information here](http://stackoverflow.com/questions/9917875/power-shell-web-scraping-ssl-tsl-issue)
This will ignor the untrusted connection. I think the best way to make the DSC secure also, is to add a parameter that ask if you download source is untrusted.

**Comment by marcvaneijk** [comment]
@paule96 Thx for your feedback. Can you please submit a pull request with your proposed code. Thanks!

**Comment by marcvaneijk** [comment]
Inactive, closing issue. @paule96 if this issue is still active, please open an new issue and reference this one. Thanks.
